project:
  type: website

website:
  title: "LF10a"
  sidebar:
    style: "docked"
    search: true
    contents:
      - href: index.qmd
        text: Home
      - href: 01_Willkommen_Struktur.qmd
        text: 01 Willkommen zu LF10a - Themen und Zeitplan
      - href: 02_Pseudocode.qmd
        text: 02 Pseudocode
      - href: 03_Algorithmen.qmd
        text: 03 Algorithmen
      - href: 04_Datenstrukturen.qmd
        text: 04 Datenstrukturen
      - href: 05_UML_Aktivitätsd-Use-Case-D.qmd
        text: 05 UML Aktivitätsdiagramm, Use-Case-Diagramm

format:
  revealjs:
    embed-resources: true
    profile: public
    include-after-body: libs/backlink.html
    css: libs/styles.css
    logo: libs/_Images/logo-AFBB.svg
    # title-slide: false   # doesn't exist!
    # theme: dracula
    # theme: blood
    # theme: league
    # slide-number: speaker
    # slide-number: true
    # google-fonts: ["Lato"]
    # font-family: "Lato"

  # html:
  #   google-fonts: ["Lato"]
  #   font-family: "Lato"

profiles:
  internal:
    # zum Zeigen, mit Bildern
  public:
    # zum Veröffentlichen, ohne manche Bilder

publish:
  gh-pages: true

